### ISSUE TITLE
startup.md incorrectly references "http://example.org"

### ISSUE THREAD

**Issue by JonathanDudzik** [yetanalytics/lrsql#180]
I was just reading over `lrsql/startup.md` and I noticed that on line 18 of that file, it says that the default name for authorityURL is "http://example.org". But I think it is in fact "http://mydomain.com" (in config/lrsql.json.example).

Thanks for all you are doing!

**Comment by kelvinqian00** [comment]
@JonathanDudzik Hi, we're going to close this issue since we've determined it was not actually an issue and we don't want to leave it open if that's the case. If you still think there is a problem, just let us know and we can re-open the issue.

**Comment by JonathanDudzik** [comment]
Hello @kelvinqian00, sounds great. Thank you for looking into it and helping me understand better. :)
