### ISSUE TITLE
HTTPS configuration with "custom PEM files" doesn't work

### ISSUE THREAD

**Issue by AlgoSolu** [yetanalytics/lrsql#194]
https://github.com/yetanalytics/lrsql/blob/d53cb5ce53d352730694a57db8abf8cdcdc3ae9b/doc/https.md#2-custom-pem-files

docker compose up logs
![Capture d’écran, le 2021-12-28 à 14 46 43](https://user-images.githubusercontent.com/7544240/147601828-ff33eb83-cc43-4581-912f-6c86923e192a.png)

Configuration file: config/lrsql.json
![Capture d’écran, le 2021-12-28 à 14 48 25](https://user-images.githubusercontent.com/7544240/147601885-02bdda7d-0118-4c45-97df-fdfe177901ba.png)

In the docker /config folder:
![Capture d’écran, le 2021-12-28 à 14 49 45](https://user-images.githubusercontent.com/7544240/147601951-3747c3cb-221d-42ba-a437-602e81ffbef2.png)

**Comment by cliffcaseyyet** [comment]
AlgoSolu,

Thank you for bringing this to our attention and providing so much detail. Would you mind also providing the `docker run` command you used to start this container so that we can attempt to reproduce (or alternatively the service defintion yml if you used compose)?

Thanks,
Cliff

**Comment by AlgoSolu** [comment]
Sorry, I simply run `docker-compose up`

**Comment by cliffcaseyyet** [comment]
That makes sense. Can you show me the yml service definition specific to the LRS in your compose, or are you just using the one [we provided in the repo](https://github.com/yetanalytics/lrsql/blob/main/docker-compose.yml)?

**Comment by AlgoSolu** [comment]
I found that variables in the docker-compose.yml doesn't work too... but the config/lrsql.json working... 

Anyway I can shared you those two files:

config/lrsql.json:
![Capture d’écran, le 2021-12-28 à 15 52 42](https://user-images.githubusercontent.com/7544240/147606373-15089704-85d1-42a5-8df2-d7beff6ad72a.png)

docker-compose.yml:
![Capture d’écran, le 2021-12-28 à 15 55 51](https://user-images.githubusercontent.com/7544240/147606446-b347fb6b-6eca-4f2c-b8d4-0574642bc5ea.png)

**Comment by cliffcaseyyet** [comment]
Ok thanks for the details. We'll try to reproduce on this end and get back to you.

**Comment by cliffcaseyyet** [comment]
Hi AlgoSolu,

Spent some time trying to debug this and cannot seem to reproduce. Obviously we have different contents for the crt files and those can't be shared, but I don't think that's quite it. To debug further i'm including an extremely simple and pared down implementation that I used locally. If you could try to reproduce with this and let me know what happens.

Config file:
![Screen Shot 2021-12-29 at 2 35 08 PM](https://user-images.githubusercontent.com/54323005/147697799-13e33ecc-33c1-4ce4-8626-bd94bff91cf8.png)

Compose:
```
services:
  lrs:
    image: yetanalytics/lrsql:v0.1.9
    volumes:
      - type: bind
        source: ~/workspace/lrsql-container-config #replace with your config dir
        target: /lrsql/config
    command:
      - /lrsql/bin/run_sqlite.sh
    ports:
      - "8080:8080"
      - "8443:8443"
```

Startup:
![Screen Shot 2021-12-29 at 2 47 27 PM](https://user-images.githubusercontent.com/54323005/147698294-b213d7f1-c0ae-443c-b7f8-a98f017373b9.png)

_Also sidenote: while working on debugging this we DID notice an issue with SSL handshake in some of our custom JRE runtimes (thanks we actually would have missed it if not debugging this one) and have patched it this morning. For that reason i'd advise ensuring you have the very latest image or explicitly using v0.1.9 as I did in the above compose. This was unrelated to your issue as even when testing with v0.1.8 we were able to pick up the certs in the mounted docker volume, but it may cause other issues after startup if you do not update._

Thanks and let me know what that turns up,
Cliff

**Comment by AlgoSolu** [comment]
Did you try with cerbot (let's encrypt)?

**Comment by cliffcaseyyet** [comment]
Interesting. I'm installing certbot now to try to reproduce. I'll get back to you.

**Comment by cliffcaseyyet** [comment]
Happy to report I did get it working with certbot. I got issued certs for a domain, and much like yourself got:

- cert1.pem
- chain1.pem
- fullchain1.pem
- privkey1.pem

Ran the same basic sample that i sent you details on but used:

```json
{
  "lrs" : {
    "adminUserDefault": "username",
    "adminPassDefault": "password",
    "authorityUrl": "http://mydomain.com"
  },
  "webserver": {
    "httpPort": 8080,
    "sslPort": 8443,
    "keyPkeyFile" : "config/debug-certs/privkey1.pem",
    "keyCertChain" : "config/debug-certs/cert1.pem,config/debug-certs/chain1.pem"
  }
}
```
And it worked like a charm. Did you try that combo?

Thanks,
Cliff

**Comment by AlgoSolu** [comment]
I rebuilt everything from scratch and I still get the message "No certificate file found. Creating a self-signed certificate!" It seems that keyPkeyFile and keyCertChain options have not worked at all, but the database configuration (in the same config file) work as expected.

It should be as simple as setting database configuration. I'm quite curious about which environment do you use to test this... How do you start the container ? Do you use only docker compose up ? 

On the next image, we can see that certificate settings inside the container are right: 

<img width="1679" alt="Capture d’écran, le 2021-12-31 à 23 25 59" src="https://user-images.githubusercontent.com/7544240/147844164-8ede7dbb-7aad-493c-9152-600eaad50c9e.png">

Maybe this is related to the environment ? 

$ uname -a
Linux 3.10.0 #1 SMP Fri Nov 20 21:47:55 MSK 2020 x86_64 x86_64 x86_64 GNU/Linux

$ docker version
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:27 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9d988398e7
  Built:            Fri May 15 00:24:05 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by cliffcaseyyet** [comment]
Hi,
Can you share the compose yml for this run as well? I posted an extremely simplified one a few messages ago that does not even use postgres in order to help us debug, and this does not look to be using it. Can you try the simple compose and simple lrsql.config posted on Dec 29, and let us know the results.

Thanks,
Cliff

**Comment by AlgoSolu** [comment]
The docker-compose.yml was the same as you published expect for the docker version (version 3.2) which is require for the volumes options. Again, this issue is related with file not founded and should work as showing in the previous comment. 

version: 3.2
services:
  lrs:
    image: yetanalytics/lrsql:v0.1.9
    volumes:
      - type: bind
        source: /root/application/config
        target: /lrsql/config
        volume:
          nocopy: true
    command:
      - /lrsql/bin/run_sqlite.sh
    ports:
      - "8080:8080"
      - "8443:8443"

**Comment by cliffcaseyyet** [comment]
Hi,

I tried this setup and still did not have an issue. I'm also running the same build sha of SQL LRS as you. My docker is slightly newer (20.10.8), and environment differences REALLY shouldn't be an issue with such a simple thing, but here is my output:

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

I also tried with your volumes option and `version: 3.2`, and still no issues. Is it at all possible there is a permissions issue with the config directory on your host?

Thanks,
Cliff

**Comment by cliffcaseyyet** [comment]
And yes I simply use `docker compose up` with the provided yml files.

**Comment by cliffcaseyyet** [comment]
The only thing I could think of is permissions on those files? Please run the following `ls -l` cmds from inside the container:

```
/lrsql # ls -l
total 48704
-rw-r--r--    1 root     root         11357 Dec 29 18:01 LICENSE
-rw-r--r--    1 root     root         22477 Dec 29 18:01 NOTICE
drwxr-xr-x    4 root     root          4096 Dec 29 18:01 admin
drwxr-xr-x    2 root     root          4096 Dec 29 18:01 bin
drwxr-xr-x    8 root     root           256 Dec 30 18:07 config
drwxr-xr-x    3 root     root          4096 Dec 29 18:01 doc
drwxr-xr-x    2 root     root          4096 Jan  6 16:52 logs
-rwxr-xr-x    1 root     root        225792 Dec 29 18:01 lrsql.exe
-rw-r--r--    1 root     root      49356737 Dec 29 18:01 lrsql.jar
-rwxr-xr-x    1 root     root        225792 Dec 29 18:01 lrsql_pg.exe
drwxr-xr-x    1 root     root          4096 Dec 29 18:02 runtimes
/lrsql # cd config
/lrsql/config # ls -l
total 20
-rw-r--r--    1 root     root           402 Dec 29 19:17 authority.json.template.example
drwxr-xr-x    6 root     root           192 Dec 30 18:09 debug-certs
-rw-r--r--    1 root     root           512 Jan  6 16:51 lrsql.json
/lrsql/config # cd debug-certs/
/lrsql/config/debug-certs # ls -l
total 20
-rw-r--r--    1 root     root          1866 Dec 30 18:07 cert1.pem
-rw-r--r--    1 root     root          3749 Dec 30 18:07 chain1.pem
-rw-r--r--    1 root     root          5615 Dec 30 18:07 fullchain1.pem
-rw-------    1 root     root          1708 Dec 30 18:07 privkey1.pem
```

**Comment by AlgoSolu** [comment]
Unfortunately, we will not reinstall lrsql for now since we decided to use another software instead. Feel free to reopen this issue.
