### ISSUE TITLE
Use regular expressions or wildcard in a query

### ISSUE THREAD

**Issue by PerryVanKuppeveld** [yetanalytics/lrsql#232]
Hi,
Is it possible to use a regular expression or any type of wildcard search in a statement query? 
For example, I would like to query all statements with a specific verb and the activity id starting with x.
Is there any documentation on this available?
Thanks in advance.

**Comment by kelvinqian00** [comment]
Hello @PerryVanKuppeveld!

This is the documentation on queries on the `/statements` endpoint: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#213-get-statements. Unfortunately, it does not support regex queries; to use your example on querying activities, the spec says:
> Only return Statements for which the Object of the Statement is an Activity with the specified id.

explicitly stating that the activity ID in your query has to match exactly the activity ID of the statements.
