### ISSUE TITLE
Add Support for HTTP only deployment

### ISSUE THREAD

**Issue by ctm8788** [yetanalytics/lrsql#242]
There currently isn't any documentation around only enabling the HTTP endpoint. 

We will be handling SSL at the Load Balancer and then sending traffic to the lrssql HTTP endpoint.

Any recommendations?

**Comment by kelvinqian00** [comment]
Hello @ctm8788,

Unfortunately there is no way to disable the HTTPS port for HTTP-only use, as documented [here](https://github.com/yetanalytics/lrsql/blob/main/doc/env_vars.md#webserver) under the `LRSQL_ENABLE_HTTP` config var. However, you should be able to just ignore the HTTPS port, without affecting any other config, and it should work fine for your use case.

**Comment by milt** [comment]
@kelvinqian00's response is satisfactory, when run behind a load balancer that is terminating HTTPS the instance HTTPS port can be safely ignored.
