### ISSUE TITLE
Unrecognized option: -J-Dfile.encoding=UTF-8

### ISSUE THREAD

**Issue by catmeme** [yetanalytics/lrsql#263]
Using `v0.4.0` via docker image `yetanalytics/lrsql:v0.4.0` with command `/lrsql/bin/run_postgres.sh`, I receive:

```
Unrecognized option: -J-Dfile.encoding=UTF-8
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Work-around, downgrade to `v0.3.9`.

**Comment by milt** [comment]
Thanks for the issue @catmeme!!! Looks like we accidentally used the incorrect Clojure-cli-wrapped version of the arg for launching from java, I missed that on review.

**Comment by milt** [comment]
Working on a patch, the quickest workaround on current main is to remove the `-J` from the front of the arg in the run script used.

**Comment by milt** [comment]
`v0.4.1-pre0` should fix this, and is up on Docker Hub now.

**Comment by catmeme** [comment]
Confirmed that `v0.4.1-pre0` fixes it.

**Comment by milt** [comment]
Proper release `v0.4.1` incorporates the fix. Thanks again!
