### ISSUE TITLE
401 Unauthorized for OIDC via Auth0

### ISSUE THREAD

**Issue by SamKosky** [yetanalytics/lrsql#270]
We're currently using Auth0 as an auth provider, and having issues getting OIDC working. I'm hoping this is just due to a lack of documentation for other auth providers and I'm doing something silly. This is what I have so far:

### LRS Config
We're using your CloudFormation templates to create the LRS instance (v0.5.1), so I've tweaked the config to:
```
  LrsInstances:
    Type: AWS::AutoScaling::LaunchConfiguration
    DependsOn: InitDBCustomResource
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    Metadata:
      AWS::CloudFormation::Init:
        ...
        02_configureLrs:
          files:
            "/opt/lrsql/config/lrsql.json":
              content: !Sub |
                {
                  "database": {
                    "dbHost": "${DBHost}",
                    "dbPort": ${DBPort},
                    "dbName": "${DBName}",
                    "dbUser": "${DBAppUserName}",
                    "dbPassword": "${InitDBCustomResource.dbAppPass}"
                  },
                  "lrs" : {
                    "adminUserDefault": "${DefaultAdminUser}",
                    "adminPassDefault": "${DefaultAdminPass}",
                    "authorityUrl": "https://lrs.dev.aveduviddhealth.xyz",
                    "oidcScopePrefix": "lrs:",
                    "oidcEnableLocalAdmin": true
                  },
                  "webserver": {
                    "httpHost": "0.0.0.0",
                    "httpPort": ${InstanceHttpPort},
                    "oidcIssuer": "<auth0_issuer>",
                    "oidcAudience": "<auth0_audience>",
                    "oidcClientId": "<auth0_client_id>",
                    "oidcClientSecret": "<auth0_client_secret>", # updated client template below to include this
                    "oidcVerifyRemoteIssuer": false             # instance kept terminating because I hadn't added the correct callback url into Auth0. FYI I've set this to "https://<my_domain>/admin/index.html"
                  }
                }
              mode: "000755"
              owner: root
              group: root
            "/opt/lrsql/config/oidc_client.json.template":
              content: !Sub |
                {
                  "authority": "{{webserver.oidc-issuer}}",
                  "client_id": "{{webserver.oidc-client-id}}",
                  "client_secret": "{{webserver.oidc-client-secret}}",
                  "response_type": "code",
                  "scope": "openid profile {{lrs.oidc-scope-prefix}}admin {{lrs.oidc-scope-prefix}}all",
                  "automaticSilentRenew": true,
                  "monitorSession": false,
                  "filterProtocolClaims": false,
                  "extraQueryParams": {
                    "audience": "{{webserver.oidc-audience}}"
                  }
                }
              mode: "000755"
              owner: root
              group: root
```

When I try logging into the admin portal via OIDC it sends a `POST` to `https://<auth0-tenant>.au.auth0.com/oauth/token` with the following `x-www-form-urlencoded` payload:
```
client_id: <auth0_client_id>
client_secret: <auth0_client_secret>
code: XXXX
redirect_uri: https://<my_domain>/admin/index.html
code_verifier: XXXX
grant_type: authorization_code
```
and returns a valid response:
```
{"access_token":"XXX","id_token":"XXX","scope":"openid profile lrs:admin lrs:all","expires_in":86400,"token_type":"Bearer"}
```
It then makes a successful call to Auth0's `/userinfo` endpoint.

The LRS then makes a `GET` request to `/admin/creds`, passing through the access token in the `Authorization` header. This returns a `401 Unauthorized`, so I can only guess that it's not validating the access token correctly.

This is what the decoded access token looks like:
```
{
  "iss": "https://medlearn-dev.au.auth0.com/",
  "sub": "google-oauth2|<google_id>",
  "aud": [
    "https://<my_domain>",
    "https://<auth0_tenant>.au.auth0.com/userinfo"
  ],
  "iat": 1674528542,
  "exp": 1674614942,
  "azp": "<auth0_client_id>",
  "scope": "openid profile lrs:admin lrs:all",
  "permissions": [
    "lrs:admin",
    "lrs:all",
    "lrs:statements/read/mine",
    "lrs:statements/write"
  ]
}
```

### xAPI Requests
I've also tried to just use this valid access token to post an xAPI statement.

Are there any examples of how to send an OAuth request to the LRS? I'm just assuming once we have a valid access token, we send it in the Authorization Header. E.g. `Authorization: Bearer <access_token>`

Request and response headers below.
```
REQUEST
> POST /xapi/statements HTTP/2
> Host: <my_domain>
> authorization: Bearer <access_token>
> x-experience-api-version: 1.0.3
> content-type: application/json
> accept: */*
> content-length: 353

RESPONSE
< HTTP/2 401 
< content-type: text/plain
```

I still receive the same `401 Unauthorized` for these requests too.

**Comment by milt** [comment]
Thanks for the excellent writeup on this. We did informally test against Auth0 during dev for the OIDC feature and there were a few rough edges but I don't immediately see anything wrong in your templates here. I'll try to hook up to our Auth0 dev account and see if I can reproduce.

**Comment by milt** [comment]
OK, after rereading your issue and doing some poking at my own Auth0 I was able to both reproduce your error and get it working with additional configuration on Auth0's end. Please excuse the explosion of complexity that follows, I will be distilling these learnings into actual step-by-step docs for Auth0 integration.

First off, on the LRS configuration/template side:
* SQL LRS's Admin Interface currently only supports the "public" (non-confidential) [Authorization Code Flow](https://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth) with PKCE. As such the client secret provided in your config is ignored and should be removed to prevent exposure. OIDC interactive auth is currently handled purely through the front-end admin SPA where we don't want to expose a secret. I'll add some commentary to the OIDC setup doc on this point.
* `oidcVerifyRemoteIssuer` simply checks (on launch + discovery refresh) that the issuer field in the discovery metadata returned from your issuer (Auth0 in this case) matches the issuer you set. You should be able to set this back to `true` if you *ensure that you've included a trailing slash* in your issuer address like: `https://milt.auth0.com/`.

Then over on Auth0 you'll need to do/confirm the following:
* Ensure the "Application Type" of your application is set to "Single Page Application" and the "Token Endpoint Authentication Method" is set to "None": 
<img width="587" alt="image" src="https://user-images.githubusercontent.com/782173/214352165-7e05664e-0c56-45a5-b4e4-aa248579c0d8.png">

* Confirm proper authorization: All SQL LRS actions are currently authorized by scopes (Auth0 calls these "permissions"). You appear to have these set up correctly judging by the tokens you posted (I see `lrs:admin` and `lrs:all` in there), I'm assuming these are present on an "API" in Auth0? You'll want to confirm that the "Identifier" for this API matches the audience you are using, and that this is the origin of your LRS. For example when I run it locally: 
<img width="590" alt="image" src="https://user-images.githubusercontent.com/782173/214357333-f1744038-40c9-4ba8-917f-4bc883efe381.png">
Ensure you've enabled Role-Based Access Control (RBAC) on the API: 
<img width="991" alt="image" src="https://user-images.githubusercontent.com/782173/214357629-4f0c6fd9-5df9-4a52-a777-d47fd2893f6a.png">
Create a role with the desired permissions: 
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/782173/214358036-01cbaaec-8636-4cf5-ba85-911d9e6b981b.png">
And finally assign that role to the user you use to log in <img width="1043" alt="image" src="https://user-images.githubusercontent.com/782173/214358316-e4a1a5c7-01d2-4cbd-8b9c-484e4a1d040f.png">

With all of that in place I am able to log in and use the LRS Admin interface after accepting the permissions grant: 
<img width="440" alt="image" src="https://user-images.githubusercontent.com/782173/214361054-0b0855cb-5d49-4617-81be-8380dd0b42bf.png">

Let me know if any/all of this works for you, happy to help with further troubleshooting!

**Comment by milt** [comment]
Oh, one further bit of advice, you'll probably want to add your allowed origins to your webserver config like:

    "allowedOrigins": ["https://<my domain>"]

We recently updated to use stricter CORS settings so you'll want that (or `allowAllOrigins`) for things to work properly too. I'm also gonna add that to the LRS template.

**Comment by SamKosky** [comment]
@milt that works like a charm! Thanks for the quick response and detailed breakdown.
