### ISSUE TITLE
OAuth scopes for activities/state endpoint

### ISSUE THREAD

**Issue by SamKosky** [yetanalytics/lrsql#278]
I have successfully setup OIDC via Auth0, and successfully posting xAPI statements with scopes `openid profile email lrs:statements/write lrs:statements/read/mine` attached.

When using the same access token to `GET` or `PUT` from the `activities/state` endpoint, I receive `403 FORBIDDEN`. 
```
> GET /xapi/activities/state?stateId=bookmark&activityId=<my_activity>&agent=<my_data> HTTP/2
> Host: <my_host>
> x-experience-api-version: 1.0.1
> authorization: Bearer <access_token>
> accept: */*

< HTTP/2 403 
< content-type: text/plain
< x-experience-api-version: 1.0.3
```

I did a quick test with increased scopes (I included everything), and the requests returned successfully.
```
> GET /xapi/activities/state?stateId=bookmark&activityId=<my_activity>&agent=<my_data> HTTP/2
> Host: <my_host>
> x-experience-api-version: 1.0.1
> authorization: Bearer <access_token>
> accept: */*

< HTTP/2 200
< content-type: application/octet-stream
< content-length: 11
< last-modified: 2023-02-01T05:54:33.443000000Z
< etag: "2ea8e2300b4d58d9d4f697e9617105f41bb78212"
< x-experience-api-version: 1.0.3
```

I'd be assuming that with the `lrs:statements/read/mine` scope, I would still be able to retrieve the state against any of my activities. However, I also realise that state objects do not contain any authority information—just the `agent`.

Are there any plans to incorporate this `lrs:statements/read/mine` scope within the `/activities` endpoints?

**Comment by SamKosky** [comment]
Thanks @milt. Just for a bit more context, we are going to be tracking Articulate (Rise) courses, which come with an xAPI wrapper. We have future plans to implement our own custom wrapper, but for now, we're dealing with what Articulate provides. And in order to allow users to resume a course, it takes advantage of the `activities/state` endpoint.

If we assign the `all` scope to each user, then they could theoretically use their access token to look at all other LRS records.

**Comment by milt** [comment]
Just to clarify I wasn't suggesting you use `all`, for the reason you mention it isn't appropriate, just confirming that it is the only scope that currently covers state.

Currently discussing the implementation of `state` with the team, specifically the pros/cons of imposing some kind of scoping/access control as the spec suggests OR just making it grant read/write to any state you have the ID and context for. The former approach seems preferable until you realize that, with an activity and agent in hand, a given client would only need to submit a statement containing them to be able to read/write to a given state. Given this we're currently leaning towards the latter approach.

Related question: do you happen to know if Articulate sends the (optional) registration UUID parameter when it accesses state?

**Comment by SamKosky** [comment]
Yes, it looks like Articulate does support `registration` as a parameter. More info [here](https://articulate.com/support/article/Implementing-Tin-Can-API-to-Support-Articulate-Content).

**Comment by milt** [comment]
Thanks! There is a PR up for this now so `state` should be supported soon. `profile` will take a little longer as we will likely have to make the scope prefix required (since it clashes with OIDC).

**Comment by milt** [comment]
Gonna close this, let us know if you have any issues using the new functionality.
