### ISSUE TITLE
Initial login fails

### ISSUE THREAD

**Issue by hendersj** [yetanalytics/lrsql#284]
Having an issue with my initial login - I'm using the latest Docker image (7d8c8bec3625), and am starting it with the following command (private values obscured):

```
docker run \
    -d \
    -p 8081:8080 \
    -e LRSQL_API_KEY_DEFAULT=xxxxx \
    -e LRSQL_API_SECRET_DEFAULT=xxxxx \
    -e LRSQL_ADMIN_USER_DEFAULT=xxxxx \
    -e LRSQL_ADMIN_PASS_DEFAULT=xxxxx \
    -e LRSQL_DB_NAME=db/lrsql.sqlite.db \
    -e LRSQL_LOG_LEVEL=info \
    -v lrsql-db:/lrsql/db \
    --name lrsql \
    yetanalytics/lrsql:latest
```

When I try to do the initial login, I enter the correct admin_user_default and admin_pass_default values, and I get an error that says

```
An unexpected error has occured!
````

(Side note:  "occured" should be "occurred" :) )

Looking at the console, I see a 403 is being returned.

I had to change the ingress port to 8081 because on my system, 8080 is in use.  Is there perhaps something I need to do to tell the system that the external port is different than the internal port, and might that be causing the issue?

**Comment by kelvinqian00** [comment]
Hello @hendersj,

If the SQL LRS webserver is on a port other than 8080, you must change the `LRSQL_HTTP_PORT` environment variable ([link to section](https://github.com/yetanalytics/lrsql/blob/main/doc/env_vars.md#webserver); it is the 11th entry in the table).

**Comment by hendersj** [comment]
Thanks for the quick answer - I now get an error that says ```Could not connect to LRS!``` - doesn't matter if I use the correct password or not.  Are there any other settings I would need to tweak?
