### ISSUE TITLE
Running LRSQL in AWS apprunner with aurora backend doesn't close connections.

### ISSUE THREAD

**Issue by jimjoes** [yetanalytics/lrsql#302]
Hi. I have setup LRSQL in a serverless-like environment using apprunner and RDS. It's working well but, as far as I can tell, the server keeps a connection pool of 10 connections open to the database so my aurora cluster never scales down to zero, even when the apprunner instance does, meaning it's costing $$$ even when not in use.

Is there some way of configuring LRSQL so that the connection pool drops to zero after an idle period? I think that will then allow my RDS to gracefully pause itself. During development, the service can be unused for days (or weeks) on end, and I'd rather not be paying AWS for all that time!

**Comment by kelvinqian00** [comment]
You should look at the HikariCP properties, particularly `LRSQL_POOL_MINIMUM_IDLE`: https://github.com/yetanalytics/lrsql/blob/main/doc/env_vars.md#hikaricp-properties

**Comment by jimjoes** [comment]
Absolute legend :) thank you. Scales down perfectly now!
