### ISSUE TITLE
I tried docker image with nginx and cannot login

### ISSUE THREAD

**Issue by xlmnxp** [yetanalytics/lrsql#303]
docker configrution:
```
docker run -d -p 8088:8088 --name lrsql
-e LRSQL_HTTP_PORT=8088
-e LRSQL_API_KEY_DEFAULT=a98914a6-0ebc-41cd-a715-5ed310130699
-e LRSQL_API_SECRET_DEFAULT=25e7fbfb-3d1c-443c-a6d6-cf5cb36c90cf
-e LRSQL_ADMIN_USER_DEFAULT=admin
-e LRSQL_ADMIN_PASS_DEFAULT=admin
-e LRSQL_DB_NAME=db/lrsql.sqlite.db
-v lrsql-db:/lrsql/db yetanalytics/lrsql:latest
```

nginx configuration:
```
server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        server_name     mydomain.com;

        ssl_certificate /etc/nginx/ssl/live/mydomain.com/fullchain.pem;
        ssl_certificate_key /etc/nginx/ssl/live/mydomain.com/privkey.pem;

        location / {
                proxy_set_header Host $http_host;
                proxy_pass          http://localhost:8088;
                proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        }
}

```

screenshot:
![image](https://github.com/yetanalytics/lrsql/assets/20779154/8e11e0df-e2e7-4e92-a375-fa345c12522a)

Response:
403 Forbidden

![image](https://github.com/yetanalytics/lrsql/assets/20779154/20eb12e8-bf03-42c0-9e17-a150d8aab8ae)

**Comment by cliffcaseyyet** [comment]
@xlmnxp My very first guess looking at this would be that we added strict CORS enforcement recently which requires an extra step for proxies such as the nginx config you have above. When the origin is misconfigured it will give a 403 like you have shown. On [this table in the docs](https://github.com/yetanalytics/lrsql/blob/main/doc/env_vars.md#webserver), pay special attention to `LRSQL_ALLOW_ALL_ORIGINS` and `LRSQL_ALLOWED_ORIGINS`. You have two options as far as I can see, you can either add the address of the nginx proxy to the allowed origins, or you can essentially turn off CORS. For a quick and dirty test I would try setting `LRSQL_ALLOW_ALL_ORIGINS` to true to see if that's the problem. Once confirmed, I recommend restricting your origins properly for any secured production deployment.

Thanks,
Cliff

**Comment by xlmnxp** [comment]
@cliffcaseyyet thank you, that fix the issue
I didn't notice the environment
