### ISSUE TITLE
Implement profile scope

### ISSUE THREAD

**Issue by davide-lucchelli** [yetanalytics/lrsql#355]
Is it possible to add "profile" scope in token scopes setting?
It is a value present in the xapi standard, is there a reason why it is not present among the selectable values?

**Comment by monkyver** [comment]
This would be very useful!

**Comment by kelvinqian00** [comment]
Thank you @davide-lucchelli  for creating the issue. Apologies for the delay in response, but we will work on its implementation.

**Comment by davide-lucchelli** [comment]
Thanks, do you already have an estimated release date?

**Comment by kelvinqian00** [comment]
@davide-lucchelli We are currently working on the feature, which you can see in PR #366

**Comment by cliffcaseyyet** [comment]
@monkyver We are almost complete with the feature, and are just doing some internal testing, along with some other priorities. I would expect a merge in the next week. Thanks.

**Comment by kelvinqian00** [comment]
@davide-lucchelli @monkyver The `activities_profile` and `agents_profile` scopes have been implemented as of v0.7.6. See #366 for more details.

**Comment by monkyver** [comment]
Thanks a lot @kelvinqian00 !
