### ISSUE TITLE
xAPI Statement Validation Issue - empty contextActivities object

### ISSUE THREAD

**Issue by GraemeSMiller** [yetanalytics/lrsql#357]
I have just setup lrsql so a partner (a popular e-learing course builder) can have us act as a Custom LRS. It was so easy - got it all working and had statements being sent in less than 30 minutes. Great out the box experience. However posting statements from partner LMS resulted in 400 - I captured the response and statement fails validation beacuse they send "contextActivities": {} as an empty object. If I remove the contextActivties and repost it in postman it instantly works.

I looked that xAPI specification and I wasn't clear whether empty object was valid or not. It says it is an optional map. Extensions property also seems like an optional map and lrsql accepts it as an empty object. Though contextActitives calls out the only valid types - where extensions doesn't (as it is for domain specific data). Context Activities says "_There are four valid context types. All, any or none of these MAY be used in a given Statement_". Also "_Every key in the contextActivities Object MUST be one of parent, grouping, category, or other._" - so I guess I can see partner reading that as empty object is acceptable as it is Empty and there are no keys. Other statement  validators pass it - but I assume yours fails it by design?

The provider is unable/unwilling to change the posted statement body. As far as I can see you use your other libraries to do the validation. Is there any way to configure the validation rules for statement so we can bypass this validation issue? Can I configure contextActivities to allow empty object? I assume not as you probably don't support bypassing what you consider valid statement?

I could potentially rewrite the body with a proxy, or fork your repo - but I wanted to check whether there was an easier option.

**Comment by cliffcaseyyet** [comment]
@GraemeSMiller Thanks for bringing this up. We will look into this and get back to you with an answer today.

Thanks, 
Cliff

**Comment by cliffcaseyyet** [comment]
@GraemeSMiller I confirmed your observation in testing and we are discussing internally. Is it possible to also share which LMS is issuing empty object bodies (if it's not a custom/internal one)? As this is a public post, you could also [email](mailto:cliff@yetanalytics.com) me if you prefer.

Thanks,
Cliff

**Comment by cliffcaseyyet** [comment]
@GraemeSMiller after some internal discussion we decided to move forward with a fix. It is ambiguous spec-wise that an LRS support empty maps but it turns out you are not the first to request. We are testing a small patch now and I will get back to you with version # when it is pushed.

**Comment by cliffcaseyyet** [comment]
@GraemeSMiller okay, that turned out to be pretty quick. Check out [this release](https://github.com/yetanalytics/lrsql/releases/tag/v0.6.9) and let us know if it resolves your LMS issues.

-Cliff

**Comment by GraemeSMiller** [comment]
The update works perfectly. Thanks for the super fast turn around time.
