### ISSUE TITLE
Conformance question

### ISSUE THREAD

**Issue by ivoloshin** [yetanalytics/lrsql#371]
Hello, I was just wondering if Yet XAPI LRS 1.0.74 listed here https://adopters.adlnet.gov/products/e695e5c9-6542-4b68-9ddf-3a3acefc8045/ is the same as this SQL LRS?

If it is not, I was also wondering if SQL LRS has gone through the conformance testing here: https://lrstest.adlnet.gov/ and if so, if there's a certificate that is available?

Thank you,
Ilya

**Comment by milt** [comment]
Hi Ilya!
The officially listed conformant LRS you mentioned is an older SaaS product, and does not apply to SQL LRS. We actually need to update that, thanks.
That said, we do run the same ADL conformance test suite (for xAPI version 1.0.3) in our CI pipeline and SQL LRS is very much conformant!
Cheers,
Milt

**Comment by ivoloshin** [comment]
Thank you for the quick response and the clarification!
