### ISSUE TITLE
XAPI Course content viewer

### ISSUE THREAD

**Issue by akhilumapathe** [yetanalytics/lrsql#376]
Hi Team, 

I would like to know how can I upload a course (XAPI compliant) into this LRS. I'm new to this domain, please accept my apologies if I'm asking the question in the wrong side. 

I see an "add content" option in a cloud platform and saw a similar approach in few others too. How is this managed in SQL LRS?

Thank you.

**Comment by cliffcaseyyet** [comment]
Hi @akhilumapathe,

An LRS (Learning Record Store) is simply a persistent store of xAPI records, usually coming from content. It's fundamentally a database of statements, and does not have any content upload functionality. Some combined xAPI suite cloud providers may add other products like content management in combination with an LRS, but this is not LRS functionality. SQL LRS implements the requirements of an LRS, and is not a combined content platform.

If you are looking for an application to which you can upload and distribute xAPI content, what you need is an LMS (Learning Management System). That is the kind of system which generates records that get stored in an LRS.

Thanks,
Cliff

**Comment by akhilumapathe** [comment]
Thankyou for this information. @cliffcaseyyet .
