### ISSUE TITLE
Is there a way to search by multiple verbs on OR condition through API

### ISSUE THREAD

**Issue by yogeshbb** [yetanalytics/lrsql#393]
I want to check if user has completed the course using a common API for different courses having different verb for completion like 'completed' or 'passed'

For example
`/xapi/statements?unwrap_html=true&verb=http://adlnet.gov/expapi/verbs/passed&related_activities=false&related_agents=false&format=ids&attachments=false`

this checks for verb 'passed' how can I pass or query for 'completed' verb in the same request, I am expecting statements which are matching either the verb 'passed' or 'completed'

OR is there a way to query on "result" key present in statement as:
`{"id": [STATEMENT_ID], "result": {"completion": true}}`

I found that for both different verb 'completed'/'passed, the '`result.completion`' is set to `true`

**Comment by milt** [comment]
Hi @yogeshbb! SQL LRS implements version 1.0.3 of the [xAPI Specification](https://github.com/adlnet/xAPI-Spec) which unfortunately does not include a way to do a boolean OR in your `/statements` query. Generally the LRS is concerned with storage of xAPI data and is not optimized for analytical use.

There are several methods you can use to do more complex queries outside of those in the spec:
* Query the underlying SQL database you are using for SQL LRS. Statement JSON is located on the `xapi_statement` table in the `payload` column. We recommend PostgreSQL for the best experience doing complex BI queries.
* Use our [Reactions](https://github.com/yetanalytics/lrsql/blob/main/doc/reactions.md) feature to detect the group of statements you want and then generate a new statement asserting that they occurred. This resulting statement can then be detected using xAPI queries.
* Set up a secondary LRS and then use [LRSPipe](https://github.com/yetanalytics/xapipe) to sync it to the first subject to the filtering criteria you define.

**Comment by yogeshbb** [comment]
Hi @milt Thanks for the quick revert on this. Just one quick question post completion can 'Reactions' feature may end up in delays to insert the new statement based on heavy load? if so need to think of 1st option of direct DB communication.

**Comment by yogeshbb** [comment]
Thanks @milt for sharing the details.
